# Default values for postgresql-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default values for postgresql-chart.

image:
  # The repository where the image of timescaledb will be pulled.
  repository: timescale/timescaledb
  # The tag to use in the repository
  tag: "latest-pg16"
  # The pull policy to use for pulling the image.
  pullPolicy: IfNotPresent
  imagePullSecrets: ""

debugMode: false

postgresqlConfig: ""

initSqlScript: ""

auth:
  user: postgres
  password: postgres
  db: postgres

service:
  type: ClusterIP
  port: 5432
  targetPort: 5432

provisioning:
  enabled: false
  sqlScript: ""

readinessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

livenessProbe:
  enabled: true
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 5
  successThreshold: 1
  failureThreshold: 3

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 10Gi
  pgData: /data/pgdata
  mountPath: /data/pgdata
  subPath: pgdata
  storageClassName: null
