apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-timescaledb-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.auth.user | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.auth.password | b64enc }}
  POSTGRES_DB: {{ .Values.auth.db | b64enc }}